### ISSUE TITLE
Problem with pyopengl !!!

### ISSUE THREAD

**Issue by v-wewei** [mmatl/pyrender#86]
Hi, @mmatl 
i seem to always get the problem below,
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    r = pyrender.OffscreenRenderer(640, 480)
  File "/home/v-wewei/anaconda3/envs/sdmaskrcnn/lib/python3.6/site-packages/pyrender/offscreen.py", line 32, in __init__
    self._create()
  File "/home/v-wewei/anaconda3/envs/sdmaskrcnn/lib/python3.6/site-packages/pyrender/offscreen.py", line 129, in _create
    self._platform.init_context()
  File "/home/v-wewei/anaconda3/envs/sdmaskrcnn/lib/python3.6/site-packages/pyrender/platforms.py", line 148, in init_context
    EGL_NO_CONTEXT, context_attributes
  File "/home/v-wewei/anaconda3/envs/sdmaskrcnn/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/home/v-wewei/anaconda3/envs/sdmaskrcnn/lib/python3.6/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 12297,
        baseOperation = eglCreateContext,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7ff8c4d6ee18>,
                <OpenGL._opaque.EGLConfig_pointer object at 0x7ff8c4d6ed90>,
                <OpenGL._opaque.EGLContext_pointer object at 0x7ff8c4da0b70>,
                <OpenGL.arrays.lists.c_int_Array_7 object at 0x7ff8af5c9048>,
        ),
        result = <OpenGL._opaque.EGLContext_pointer object at 0x7ff8c4902e18>
)

could you help to give me the solution for this opengl problem?
Thanks advance.

**Comment by ahangchen** [comment]
I met this problem too. any solution?

**Comment by v-wewei** [comment]
i found this problem cas caused by the mistake when i install the nvidia-driver, reinstall the driver make everything works as expected.

**Comment by lan786** [comment]
@v-wewei  How you install new driver? From run file?

**Comment by MengXinChengXuYuan** [comment]
@v-wewei I also met this, are you running the code on a server machine?
And I just don't understand, what mistake can be made installing the nvidia-driver ? :(

**Comment by v-wewei** [comment]
@lan786 @MengXinChengXuYuan  
i run my program on a local machine , not on a remote server. 
i install the nvidia-driver with openGL installed, then i am able to overcome this problem. sorry for so late to reply your question. Also you need to check the version with opengl with cm: "glxinfo | grep OpenGL" for the machine.  you can have a try if you miss some of the step above. 
Best wish !

**Comment by lcit** [comment]
I run into this problem on a kubernetes pod running Ubuntu 18.04.5 LTS. I assume Nvidia driver are installed correctly as I can use GPU computation and nvidia-smi.

The error is EGL_BAD_MATCH=12297 and it is thrown by eglCreateContext. This function in my case was called here https://github.com/mmatl/pyrender/blob/94f1aa65fce04dc3f0a5f7d88ea4da7482959e1f/pyrender/platforms/egl.py#L186

after several attempts I found that the problem was the OpenGL version. For some reason by default the machine was running version 3.3 but pyrender expects version 4.1 as for here: https://github.com/mmatl/pyrender/blob/94f1aa65fce04dc3f0a5f7d88ea4da7482959e1f/pyrender/platforms/egl.py#L156

in theory my machine should have access to OpenGL 4.x but the version used is 3.3 (you can check with glxinfo). To fix this I had to use this macro in front of the script to run `MESA_GL_VERSION_OVERRIDE=4.1 python code.py` 

At this point I had another problem. My machine for some reason has GL_MAX_SAMPLES=1 which seems to be the upperbound on the number of samples for multisampling. In pyrender the number of samples is set to 4 in both line 1091 and 1096: https://github.com/mmatl/pyrender/blob/94f1aa65fce04dc3f0a5f7d88ea4da7482959e1f/pyrender/renderer.py#L1091
I had to change these two to 1.

I have no clue why GL_MAX_SAMPLES is just 1. Should be much higher.

**Comment by vegetable09** [comment]
@lcit Thanks! it works for me!

**Comment by Fabioo29** [comment]
@lcit thanks a lot! It works now!
